- name: Check supported family
  ansible.builtin.fail:
    msg: "This role supports {{ supported_distros | join(', ') }} families, got {{ ansible_os_family }}"
  tags:
    - install
  when: 
    - ansible_distribution not in supported_distros

- name: Debian based distros
  block:
    - name: Install zabbix-agent2
      ansible.builtin.package:
        name: zabbix-agent2
        state: present
  tags:
    - install
