zabbix_version: 7.0

zabbix_agent2:
  mandatory:
    server: zabbix.server
  # all lower are optional
  hostname: "{{ inventory_hostname }}"
  log_type: file
  debug_level: 3
  listen_port: 10050
  listen_ip: 0.0.0.0
  server_active: zabbix.server
  buffer:
    size: 1024
    persisten:
      enable: 1
      period: 1h
      file: /tmp/zabbix-agent2.sql
  tls:
    connect: cert
    ca_path: /etc/zabbix/pki/ca.crt
    cert_file: /etc/zabbix/pki/agent2.crt
    key_file: /etc/zabbix/pki/agent2.key
    psk_identity: identiti
    psk_file: /etc/zabbix/pki/agent2-psk.key
